import mongoose from 'mongoose';

const doctorSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
    },
    registrationNumber: {
      type: String,
      required: true,
      unique: true, // medical registration number — must be unique per doctor
    },
    degree: {
      type: String,
      required: true,
    },
    specialization: {
      type: String,
      required: true,
    },
    experience: {
      type: Number, // years of experience
      required: true,
    },
    loginId: {
      type: String,
      required: true,
      unique: true, // generated by admin, used for doctor login
    },
    password: {
      type: String,
      required: true, // stored as a bcrypt hash, same as Patient
    },
    isActivated: {
      type: Boolean,
      default: false, // becomes true after doctor completes first-time setup
    },
    currentMonthLocked: {
      type: Boolean,
      default: false, // becomes true once activated — current-month changes then require admin
    },
  },
  {
    timestamps: true,
  }
);

export const Doctor = mongoose.model('Doctor', doctorSchema);